### ISSUE TITLE
NavigationRestrictions/UpdateRestrictions vs. UpdateRestrictions 

### ISSUE THREAD

**Issue by BerSie** [oasis-tcs/odata-vocabularies#195]
Thanks for explaining the annotations in wrt restrictions in the Capabilities vocabulary in https://github.com/oasis-tcs/odata-vocabularies/blob/main/examples/Org.OData.Capabilities.V1.capabilities.md.
There is one point I don't feel confident why it's explained in that way: the second code example shows NavigationRestrictions/UpdateRestrictions/NoneUpdatableProperties with target Headers and NavigationProperty Items and additionally UpdateRestrictions/NoneUpdatableProperties with target Headers/Items. And in the text above it's mentioned: `the NonUpdatableProperties property in the deeper UpdateRestrictions is favored over its commented-out namesake in the higher-up NavigationRestrictions,`
... and I wonder why is that? The documentation of NavigationProperty of the NavigationRestrictions says: `The target path of a NavigationRestrictions annotation followed by this navigation property path addresses the resource to which the other properties of NavigationPropertyRestriction apply` This would mean for the above mentioned example it addresses Headers/Items. So why should it win over the annotation that addresses Headers/Items?

**Comment by HeikoTheissen** [comment]
Both annotations are syntactically possible, and if both were present with different lists of property names, these lists would have to be united, because both are valid ways to declare a property non-updatable.

But in order to avoid such cases, the specification says that only the second version (with target `Headers/Items`) shall be used (is *favored*). The other one is *discouraged*, but if it is present (or even both are present), they are treated as valid annotations. There are no *winning rules* for such a case.

**Comment by BerSie** [comment]
Thank you, @HeikoTheissen !
