### ISSUE TITLE
Does InsertRestrictionsType allow PropertyPath for Insertable property?

### ISSUE THREAD

**Issue by gregorwolf** [oasis-tcs/odata-vocabularies#82]
Hello OData Vocabularies Team,

the specification for [InsertRestrictionsType](https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Capabilities.V1.md#InsertRestrictionsType) defines Boolean for the property Insertable. But in the SAPUI5 Documentation at [Defining and Adapting Sections](https://sapui5.hana.ondemand.com/#/topic/facfea09018d4376acaceddb7e3f03b6) in the section "Rendering a Smart Table in a Section" there is this example:

`<PropertyValue Property="Insertable" Path="Insertable"/>`

Is SAPUI5 ahead of the specification or do they not follow the specification?

Best regards
Gregor

**Comment by ralfhandl** [comment]
Hi @gregorwolf,

If the `Path` expression points to a Boolean property, all is fine.

You can always use `Path` expressions in annotations instead of constant values as long as the type of the `Path` target is compatible, i.e. is identical or can be implicitly cast to the declared type of the term or term property. 

Kind regards 
Ralf

**Comment by gregorwolf** [comment]
Thank you, Ralf
